# Generated by Django 2.1.5 on 2019-02-12 17:21

from django.db import migrations, models
import part1.models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0002_auto_20190211_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=part1.models.image_folder),
        ),
    ]
