# Generated by Django 2.1.7 on 2019-02-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0004_auto_20190213_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='part1.CartItem'),
        ),
    ]
