# Generated by Django 2.1.7 on 2019-02-25 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('part1', '0010_auto_20190225_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare',
            field=models.ManyToManyField(related_name='compare', to=settings.AUTH_USER_MODEL),
        ),
    ]
