# Generated by Django 2.1.7 on 2019-02-26 16:20

from django.conf import settings
from django.db import migrations, models
import part1.models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0011_product_compare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=part1.models.image_folder)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=True, to='part1.Brand')),
                ('category', models.ForeignKey(on_delete=True, to='part1.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='compare',
            field=models.ManyToManyField(blank=True, related_name='compare', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='shared',
            field=models.ManyToManyField(blank=True, to='part1.Shared'),
        ),
    ]
