# Generated by Django 2.1.7 on 2019-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0012_auto_20190226_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shared',
        ),
        migrations.AddField(
            model_name='product',
            name='shared_with_me',
            field=models.ManyToManyField(to='part1.Shared'),
        ),
    ]
