# Generated by Django 2.1.7 on 2019-02-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0015_auto_20190227_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
