# Generated by Django 2.1.7 on 2019-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0016_relation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='relationss',
        ),
        migrations.AddField(
            model_name='relation',
            name='relations',
            field=models.ManyToManyField(blank=True, null=True, related_name='relationss', to='part1.Product'),
        ),
    ]
